name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on pushes to tags like v1.0, v1.0.1, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version available

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build # Install the 'build' package to create distributions

    - name: Build package
      run: python -m build # This will create .whl and .tar.gz files in the 'dist/' directory

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }} # Your PyPI API token secret
        user: __token__ 
